name: RewardsX
version: '2026.08.18'
api-version: '1.19'
description: RewardsX Minecraft plugin for Paper
authors:
  - R_Developing

main: net.r_developing.rewardsx.Plugin
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true