name: RewardsX
main: net.r_developing.rewardsx.Main
version: 2026.05.09
api-version: '1.19'
description: RewardsX Minecraft plugin for Paper
authors:
  - R_Developing

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true